delete from G_FUNS where FUN_ID in 
('CIPS_10801',
'CIPS_108_MADE',
'CIPS_108_RCV_NOTICE',
'CIPS_382_RCV',
'CIPS_TXN_SUMMARY_11201',
'GNO_SEND_ASYN',
'ONECERT_ADD_ASSIGNMENT_API',
'ONECERT_CREATE_ACCOUNT_API',
'SCB_15300',
'SCB_6199',
'SCB_6299',
'SCB_CIPS906_GEN_CSV',
'SCB_CIPS_PDNG_NOTICE',
'SCB_CIPS_TXN_SUMMARY_11201_CUST',
'SCB_CIPS_TXN_SUMMARY_11202_CUST',
'SCB_GENTSAASDATATOTXT',
'SCB_RESND_NOROUTE_MSG',
'SCB_SEND_EMAILATTACHMENT',
'SCB_TRANS_FILE_TOEMAIL',
'SCB_CIPS_301_109_SERVICE',
'CIPS_108_RCV',
'DBI_CIPS_REMIT_PATH_DELETE',
'DBI_CIPS_REMIT_PATH_FIND',
'DBI_CIPS_REMIT_PATH_INSERT',
'DBI_CIPS_REMIT_PATH_LOCK',
'DBI_CIPS_REMIT_PATH_TMP_DELETE',
'DBI_CIPS_REMIT_PATH_TMP_FIND',
'DBI_CIPS_REMIT_PATH_TMP_INSERT',
'DBI_CIPS_REMIT_PATH_TMP_LOCK',
'DBI_CIPS_REMIT_PATH_TMP_UPDATE',
'DBI_CIPS_REMIT_PATH_UPDATE',
'DBI_CIPS_382_LIST_DELETE',
'DBI_CIPS_382_LIST_FIND',
'DBI_CIPS_382_LIST_INSERT',
'DBI_CIPS_382_LIST_LOCK',
'DBI_CIPS_382_LIST_UPDATE',
'DBI_CIPS_382_LOCK',
'DBI_CIPS_382_UPDATE',
'DBI_CIPS_382_DELETE',
'DBI_CIPS_382_FIND',
'DBI_CIPS_382_INSERT',
'DBI_CIPS_108_DELETE',
'DBI_CIPS_108_DLIST_DELETE',
'DBI_CIPS_108_DLIST_FIND',
'DBI_CIPS_108_DLIST_INSERT',
'DBI_CIPS_108_DLIST_LOCK',
'DBI_CIPS_108_DLIST_UPDATE',
'DBI_CIPS_108_FIND',
'DBI_CIPS_108_INSERT',
'DBI_CIPS_108_LIST_DELETE',
'DBI_CIPS_108_LIST_FIND',
'DBI_CIPS_108_LIST_INSERT',
'DBI_CIPS_108_LIST_LOCK',
'DBI_CIPS_108_LIST_UPDATE',
'DBI_CIPS_108_LOCK',
'DBI_CIPS_108_UPDATE',
'CIPS_UPDATEREMITPATH');
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_10801', 'CIPS_10801', 'CIPS', 1, 'libcips_txn.so', null, null, '00', null, '20231017144705', '20231017144705', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_108_MADE', 'CIPS_108_MADE', 'CIPS', 2, 'libcips_api.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_108_RCV_NOTICE', 'CIPS_108_RCV_NOTICE', 'CIPS', 0, 'libcips_notice.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_382_RCV', 'CIPS_382_RCV', 'CIPS', 0, 'libcips_rcv.so', null, null, '00', null, '20230714100654', '20230714100654', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_TXN_SUMMARY_11201', 'CIPS_TXN_SUMMARY_11201', 'CIPS', 4, 'libcips_inq.so', null, null, '00', null, '20221209145215', '20221209145215', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('GNO_SEND_ASYN', 'GNO_Send_Asyn', 'GNOTICE', 1, 'libgno_service_core.so', null, null, '00', null, '20151023145826', '20151023145826', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ONECERT_ADD_ASSIGNMENT_API', 'ONECERT_ADD_ASSIGNMENT_API', 'SCB', 1, 'libscb_bank.so', null, null, '00', null, '20231109160300', '20231109160300', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ONECERT_CREATE_ACCOUNT_API', 'ONECERT_CREATE_ACCOUNT_API', 'SCB', 1, 'libscb_bank.so', null, null, '00', null, '20231109160300', '20231109160300', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_15300', 'SCB_15300', 'SCB', 1, 'libscb_txn.so', null, null, '00', null, '20231017144705', '20231017144705', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_6199', 'SCB_6199', 'SCB', 1, 'libscb_txn.so', null, null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_6299', 'SCB_6299', 'SCB', 1, 'libscb_txn.so', null, null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_CIPS906_GEN_CSV', 'SCB_CIPS906_GEN_CSV', 'SCB', 0, 'libscb_task.so', null, null, '00', null, '20240520184515', '20240520184515', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB_CIPS_PDNG_NOTICE', 'SCB', null, 'libscb_notice.so', null, null, '00', null, '2024017164700', '2024017164700', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_CIPS_TXN_SUMMARY_11201_CUST', 'SCB_CIPS_TXN_SUMMARY_11201_Cust', 'SCB', 4, 'libscb_cust.so', null, null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_CIPS_TXN_SUMMARY_11202_CUST', 'SCB_CIPS_TXN_SUMMARY_11202_Cust', 'SCB', 0, 'libscb_cust.so', null, null, '00', null, '20240626163000', '20240626163000', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_GENTSAASDATATOTXT', 'SCB_GenTsaasDataToTxt', 'SCB', 0, 'libscb_common.so', null, null, '00', null, '20220427230456', '20220427230456', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_RESND_NOROUTE_MSG', 'SCB_RESND_NOROUTE_MSG', 'SCB', 1, 'libscb_task.so', null, null, '00', null, '20230912172957', '20220427230457', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_SEND_EMAILATTACHMENT', 'SCB_Send_EmailAttachment', 'SCB', 8, 'libscb_common.so', null, null, '00', null, '20220427230456', '20220427230456', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_TRANS_FILE_TOEMAIL', 'SCB_TRANS_FILE_TOEMAIL', 'SCB', 1, 'libscb_task.so', null, null, '00', null, '20220427230457', '20220427230457', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_CIPS_301_109_SERVICE', 'SCB_Generate301BasedOn109_w', 'SCB', 0, 'libscb_common.so', null, null, '00', null, '20240621172000', '20240621172000', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_108_RCV', 'CIPS_108_RCV', 'CIPS', 0, 'libcips_rcv.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_DELETE', 'DBI_CIPS_REMIT_PATH_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_FIND', 'DBI_CIPS_REMIT_PATH_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_INSERT', 'DBI_CIPS_REMIT_PATH_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_LOCK', 'DBI_CIPS_REMIT_PATH_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_TMP_DELETE', 'DBI_CIPS_REMIT_PATH_TMP_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_TMP_FIND', 'DBI_CIPS_REMIT_PATH_TMP_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_TMP_INSERT', 'DBI_CIPS_REMIT_PATH_TMP_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_TMP_LOCK', 'DBI_CIPS_REMIT_PATH_TMP_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_TMP_UPDATE', 'DBI_CIPS_REMIT_PATH_TMP_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_REMIT_PATH_UPDATE', 'DBI_CIPS_REMIT_PATH_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_LIST_DELETE', 'DBI_CIPS_382_LIST_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_LIST_FIND', 'DBI_CIPS_382_LIST_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_LIST_INSERT', 'DBI_CIPS_382_LIST_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_LIST_LOCK', 'DBI_CIPS_382_LIST_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_LIST_UPDATE', 'DBI_CIPS_382_LIST_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_LOCK', 'DBI_CIPS_382_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_UPDATE', 'DBI_CIPS_382_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_DELETE', 'DBI_CIPS_382_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_FIND', 'DBI_CIPS_382_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_382_INSERT', 'DBI_CIPS_382_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20230714100652', '20230714100652', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_DELETE', 'DBI_CIPS_108_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_DLIST_DELETE', 'DBI_CIPS_108_DLIST_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_DLIST_FIND', 'DBI_CIPS_108_DLIST_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_DLIST_INSERT', 'DBI_CIPS_108_DLIST_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_DLIST_LOCK', 'DBI_CIPS_108_DLIST_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_DLIST_UPDATE', 'DBI_CIPS_108_DLIST_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_FIND', 'DBI_CIPS_108_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_INSERT', 'DBI_CIPS_108_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_LIST_DELETE', 'DBI_CIPS_108_LIST_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_LIST_FIND', 'DBI_CIPS_108_LIST_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_LIST_INSERT', 'DBI_CIPS_108_LIST_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_LIST_LOCK', 'DBI_CIPS_108_LIST_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_LIST_UPDATE', 'DBI_CIPS_108_LIST_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_LOCK', 'DBI_CIPS_108_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_108_UPDATE', 'DBI_CIPS_108_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_UPDATEREMITPATH', 'CIPS_UpdateRemitPath', 'CIPS', 2, 'libcips_batch.so', null, null, '00', null, '20231017144703', '20231017144703', null, null, null, null, null);

delete from G_INQ_CFG where SQL_ID='053092001';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '053092001', 'SELECT
seq_no,
  txn_seq_no,
  work_date,
  center_date,
  txn_dir,
  msg_id,
  tsaas_ref_no,
  ref_no,
  CASE WHEN txn_dir = ''1''
    THEN rcv_st_brno
  ELSE snd_st_brno END   AS op_st_brno,
  CASE WHEN txn_dir = ''1''
    THEN rcv_st_brname
  ELSE snd_st_brname END AS op_st_brname,
  pboc_status,
  tsaas_rsp_info,
  tsaas_status,
  cers_status,
  BIZ_PROC_INFO,
  comm_status,
  txn_status,
  upd_time,
  made_user,
  made_time,
  apv_user,
  apv_time
FROM @cips_info
WHERE msg_no = ''309'' AND REF_NO = :"REF_NO" AND msg_id = :"MSG_ID" AND txn_dir = :"TXN_DIR" AND
      center_date >= :"START_CENTER_DATE" AND center_date <= :"END_CENTER_DATE"  AND work_date >= :"START_WORK_DATE" AND work_date <= :"END_WORK_DATE" AND
      TXN_SEQ_NO like ''%'' || :"TXN_SEQ_NO" || ''%''
ORDER BY upd_time', null, 'CIPS', null, null, null, null, null, null, null, null);

--清算机构借贷通知查询SCPAY
delete from G_INQ_CFG where SQL_ID='051530001';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB', '051530001', 'SELECT A.CENTER_DATE, A.DAY_NIGHT_FLG, A.TXN_SEQ_NO, A.MSG_ID, A.AMT, A.REF_NO, A.CIPS_DC_FLAG, B.COMM_STATUS, B.TXN_STATUS, B.PBOC_STATUS, B.BIZ_PROC_INFO, A.PAYER_ST_BRNO, A.PAYER_ST_BRNAME, A.PAYEE_ST_BRNO, A.PAYEE_ST_BRNAME,B.CORE_FWD_FLAG_SCPAY,B.CORE_PROC_STATUS_SCPAY FROM CIPS_153 A, CIPS_TXN B WHERE A.TXN_SEQ_NO = B.TXN_SEQ_NO AND A.CENTER_DATE >= :"START_CENTER_DATE" AND A.CENTER_DATE <= :"END_CENTER_DATE" AND A.AMT >= :"START_AMT" AND A.AMT <= :"END_AMT" AND A.MSG_ID LIKE ''%'' || :"MSG_ID" || ''%'' AND B.PBOC_STATUS = :"PBOC_STATUS" AND A.DAY_NIGHT_FLG = :"DAY_NIGHT_FLG" AND A.TXN_SEQ_NO = :"TXN_SEQ_NO" AND A.REF_NO = :"REF_NO" AND A.CIPS_DC_FLAG = :"CIPS_DC_FLAG" ORDER BY B.TXN_SEQ_NO DESC', null, 'CIPS', null, null, null, null, null, null, null, null);

--VIP账号维护查询VIP类型
delete from G_INQ_CFG where SQL_ID='050319901';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB', '050229801', 'SELECT t.VIP_TYPE,
    t.VIP_ACTNO,
    t.VIP_NAME,
    t.VIP_LEVEL,
    t.REMARKS,
    case t.MOD_STATUS when ''00'' then ''正常'' else ''修改中'' end as MOD_STATUS,
    t.CRT_USER,
    t.CRT_TIME,
    t.UPD_USER,
    t.UPD_TIME,
    t.APV_USER,
    t.APV_TIME
FROM
    SCB_VIPACCT_INFO t
WHERE
    1=1
AND t.VIP_ACTNO=:"VIP_ACTNO"
', null, 'SCB', null, null, null, null, null, null, null, null);

--VIP账户维护VIP类型
delete from G_INQ_CFG where SQL_ID='050319901';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB', '050319901', 'SELECT t.VIP_TYPE,
    t.VIP_ACTNO,
    t.VIP_NAME,
    t.VIP_LEVEL,
	t.REMARKS,
	t.CRT_TIME,
	t.UPD_TIME
FROM
    SCB_VIPACCT_INFO t
WHERE
    1=1
AND VIP_ACTNO=:"VIP_ACTNO"
AND VIP_NAME=:"VIP_NAME"
AND VIP_LEVEL=:"VIP_LEVEL"
AND VIP_TYPE=:"VIP_TYPE"', null, 'SCB', null, null, null, null, null, null, null, null);

delete from G_INQ_CFG where SQL_ID='050329901';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050329901', 'SELECT
*
FROM
    SCB_VIPACCT_INFO_TMP
WHERE
1=1
AND VIP_ACTNO=:"VIP_ACTNO"', null, 'CIPS', null, null, null, null, null, null, null, null);


delete from G_SERVICES where SERVICE_ID in 
('CIPS_10801',
'GMON_MQ',
'ONECERT_ADD_ASSIGNMENT_API',
'ONECERT_CREATE_ACCOUNT_API',
'SCB_15300',
'SCB_6199',
'SCB_6299',
'SCB_CIPS906_GEN_CSV',
'SCB_CIPS_PDNG_NOTICE',
'SCB_GenTsaasDataToTxt',
'SCB_RESND_NOROUTE_MSG',
'SCB_TRANS_FILE_TOEMAIL');
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_10801', 'CIPS', null, null, null, 'CIPS_MADE_MAIN', 'CIPS_HTTP', 'SERVICE', null, null, null, '费用扣款通知录入', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('GMON_MQ', 'GMONITOR', null, null, null, 'GMON_ServiceMQ', 'DEFAULT', 'SERVICE', null, null, 0, 'MQ数据处理服务', null, '00', 0, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ONECERT_ADD_ASSIGNMENT_API', 'SCB', null, null, null, 'ONECERT_ADD_ASSIGNMENT_API', 'DEFAULT', 'SERVICE', null, null, null, 'ONECERT_ADD_ASSIGNMENT_API', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ONECERT_CREATE_ACCOUNT_API', 'SCB', null, null, null, 'ONECERT_CREATE_ACCOUNT_API', 'DEFAULT', 'SERVICE', null, null, null, 'ONECERT_CREATE_ACCOUNT_API', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_GenTsaasDataToTxt', 'SCB', null, null, null, 'SCB_GenTsaasDataToTxt', 'SCB_CIPS_AUTO_CHARGES', 'SERVICE', null, null, null, null, null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB', null, null, null, 'SCB_CIPS_PDNG_NOTICE', 'DEFAULT', 'SERVICE', null, null, null, '检查清算排队数据提醒函数', null, '00', 0, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_CIPS906_GEN_CSV', 'SCB', null, 'NULL', 'NULL', 'SCB_CIPS906_GEN_CSV', 'DEFAULT', 'SERVICE', null, null, null, '906变更报文生成csv文件通过脚本传输tsaas', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_RESND_NOROUTE_MSG', 'SCB', null, 'NULL', 'NULL', 'SCB_RESND_NOROUTE_MSG', 'DEFAULT', 'SERVICE', null, null, null, '定时发送未发送到CIPS的报文', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_TRANS_FILE_TOEMAIL', 'SCB', null, null, null, 'SCB_TRANS_FILE_TOEMAIL', 'SCB_CIPS_AUTO_CHARGES', 'SERVICE', null, null, null, '定时发送邮件通知前一日来往账交易信息', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_15300', 'SCB', null, null, null, 'TLR_MADE_MAIN', 'CIPS_HTTP', 'SERVICE', null, null, null, '重发清算机构借贷通知报文', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_6199', 'SCB', null, 'SCB_6199_REQ', 'SCB_6199_RSP', 'TLR_MADE_MAIN', 'DEFAULT', 'SERVICE', null, null, null, '黑名单维护', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('SCB_6299', 'SCB', null, 'SCB_6299_REQ', 'SCB_6299_RSP', 'TLR_APV_MAIN', 'DEFAULT', 'SERVICE', null, null, null, '黑名单维护审核', null, '00', null, null, null, null, null, null, null, null);
------------------------------------------
-- 每隔30分钟发送清算排队业务信息通知
------------------------------------------
--定时任务部分
INSERT INTO G_LOOP_CALL (NODE_ID, CORP_ID, CALL_ID, SYSTEM, CALL_DESC, CALL_SERVICE, CALL_REQ, START_TIME, END_TIME, INTERVAL_TIME, NEXT_TIME, STATUS, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('DEV', 'SCB', 'SCB_CIPS_PDNG_NOTICE', 'CIPS', '定时发送清算排队邮件', 'SCB_CIPS_PDNG_NOTICE', '{"CORP_ID": "SCB"}', '000000', '240000', 1800, '20260312153556', '1', null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB', null, null, null, 'SCB_CIPS_PDNG_NOTICE', 'DEFAULT', 'SERVICE', null, null, null, '检查清算排队数据提醒函数', null, '00', 0, null, null, null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB_CIPS_PDNG_NOTICE', 'SCB', null, 'libscb_notice.so', null, null, '00', null, '2024017164700', '2024017164700', null, null, null, null, null);

--邮件部分
INSERT INTO GNO_TPL (TPL_ID, TPL_LANG, CHL_ID, MSG_FMT, MSG_TITLE, TPL_DATA, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, MOD_STATUS, SEQ_NO) VALUES ('SCB_QUEUESETTLE_PDNG', 'cn', 'EMAIL', 'text', 'SCB_QUEUESETTLE_PDNG', '检查清算排队数据提醒

排队数量：$(DATA.IN.PDNG_COUNT)
排队内容：
$(DATA.IN.CONTENT)', '检查清算排队数据提醒函数', '20240618114217', '20240617165145', null, null, null, null, null, 'test', '20240617', 'test', '20240618', 'test', '20240618', '20240618114226', '00', '20240618000000843215');

INSERT INTO GNO_TOPIC (TOPIC, TPL_ID, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, MOD_STATUS, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, SEQ_NO)
VALUES ('SCB_QUEUESETTLE_PDNG', 'SCB_QUEUESETTLE_PDNG', '清算排队提醒函数', null, '20240618113807', null, null, null, null, null, '00', 'test', '20240618', null, null, 'test', '20240618', '20240618113817', null);

INSERT INTO G_ROUTE (CORP_ID, NODE_ID, ROUTE_ID, ROUTE_KEY, ROUTE_DATA, ROUTE_RESULT, ROUTE_TYPE, ROUTE_MODE, IDX, SYSTEM, REMARKS, STATUS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('ALL', 'ALL', 'GNO_NOTICE', 'SCB_QUEUESETTLE_PDNG', '$(REQ.HEAD.MSG_SENDER)_$(REQ.HEAD.MSG_TYPE)', 'SCB_QUEUESETTLE_PDNG', 'SERVICE', 'R', 4, 'GNOTICE', '检查清算排队数据提醒', '00', '20240617163000', '20240617163000', null, null, null, null, null);


------------------------------------------
-- 自动发起（T-1）日索费信息提醒
------------------------------------------
-- 定时任务部分
INSERT INTO G_LOOP_CALL (NODE_ID, CORP_ID, CALL_ID, SYSTEM, CALL_DESC, CALL_SERVICE, CALL_REQ, START_TIME, END_TIME, INTERVAL_TIME, NEXT_TIME, STATUS, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('DEV', 'SCB', 'SCB_CIPS_CHARGES_AUTO_NOTICE', 'CIPS', '自动发起（T-1）日索费信息提醒', 'SCB_CIPS_CHARGES_AUTO_NOTICE', '{"CORP_ID": "SCB", "SYSTEM": "SCB"}', '090000', '100000', 86400, '20260313090000', '1', null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_CHARGES_AUTO_NOTICE', 'SCB', null, 'NULL', 'NULL', 'SCB_CIPS_CHARGES_AUTO_NOTICE', 'DEFAULT', 'SERVICE', null, null, null, '发送索费信息邮件通知', null, '00', null, null, null, null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_CHARGES_AUTO_NOTICE', 'SCB_CIPS_CHARGES_AUTO_NOTICE', 'SCB', 1, 'libscb_task.so', null, null, '00', null, '20230922094702', '20230922094702', null, null, null, null, null);

--邮件部分
INSERT INTO GNO_TPL (TPL_ID, TPL_LANG, CHL_ID, MSG_FMT, MSG_TITLE, TPL_DATA, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, MOD_STATUS, SEQ_NO) VALUES ('SCB_109_INFORMATION_RCV', 'cn', 'EMAIL', 'text', '索费往账信息提醒', '索费往账信息提醒

数据统计日期：$(DATA.IN.WORK_DATE)
索费总笔数：$(DATA.IN.TOTAL_COUNT)
索费未收款金额：$(DATA.IN.CTRL_SUM_AMT) 元
索费付款金额：$(DATA.IN.RECEIPT_AMT) 元', null, '20230925170331', '20230925154237', null, null, null, null, null, 'test', '20230925', 'test', '20230925', 'test', '20230925', '20230925170345', '00', '20230928000000743320');

INSERT INTO GNO_TOPIC (TOPIC, TPL_ID, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, MOD_STATUS, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, SEQ_NO)
VALUES ('SCB_QUEUESETTLE_PDNG', 'SCB_QUEUESETTLE_PDNG', '清算排队提醒函数', null, '20240618113807', null, null, null, null, null, '00', 'test', '20240618', null, null, 'test', '20240618', '20240618113817', null);

INSERT INTO G_ROUTE (CORP_ID, NODE_ID, ROUTE_ID, ROUTE_KEY, ROUTE_DATA, ROUTE_RESULT, ROUTE_TYPE, ROUTE_MODE, IDX, SYSTEM, REMARKS, STATUS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('ALL', 'ALL', 'GNO_NOTICE', 'SCB_QUEUESETTLE_PDNG', '$(REQ.HEAD.MSG_SENDER)_$(REQ.HEAD.MSG_TYPE)', 'SCB_QUEUESETTLE_PDNG', 'SERVICE', 'R', 4, 'GNOTICE', '检查清算排队数据提醒', '00', '20240617163000', '20240617163000', null, null, null, null, null);
--增添vip数据字典
INSERT INTO "GPAY_BASE_DIC"("SYS_ID", "CORP_ID", "GROUP_ID", "DATA_SORT_ID", "GROUP_DESC", "DATA_VALUE", "DATA_DESC", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('05', '0000', 'VIP_0000', '1', 'VIP账户类型', '1', 'Customer_Account', NULL, NULL, NULL, NULL, NULL);

INSERT INTO "GPAY_BASE_DIC"("SYS_ID", "CORP_ID", "GROUP_ID", "DATA_SORT_ID", "GROUP_DESC", "DATA_VALUE", "DATA_DESC", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('05', '0000', 'VIP_0000', '2', 'VIP账户类型', '2', 'BIC_Code', NULL, NULL, NULL, NULL, NULL);

--新增参数
INSERT INTO G_PARAS (SYSTEM, CORP_ID, ORG_ID, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, EXPIRE, OP_TYPE, OP_STATUS, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'SCB', 'ALL', 'SCB_HK_VIP_SWITCH', 'on', 'on(使用HK的VIP逻辑)，off(使用CN的VIP逻辑)', '02', null, '00', null, null, null, null, null, null, 'dydy', '20260311', '20260311174056', null, null, null, null, null, null);

--修改vip维护页面的sql-050319901

DELETE FROM G_INQ_CFG WHERE SQL_ID='050319901';

INSERT INTO "G_INQ_CFG"("CORP_ID", "SQL_ID", "SQL_STRING", "DETAIL_SQL_STRING", "SYSTEM", "REMARKS", "UPD_TIME", "CRT_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('SCB', '050319901', 'SELECT
    t.VIP_TYPE,
    t.VIP_ACTNO,
    t.VIP_NAME,
    t.VIP_LEVEL,
	t.REMARKS,
	t.CRT_TIME,
	t.UPD_TIME
FROM
    SCB_VIPACCT_INFO t
WHERE
    1=1
AND VIP_TYPE=:"VIP_TYPE"
AND upper(VIP_ACTNO)=upper(:"VIP_ACTNO")
AND VIP_NAME=:"VIP_NAME"
AND VIP_LEVEL=:"VIP_LEVEL"', NULL, 'SCB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--修改vip维护审核页面的sql-050329901

DELETE FROM G_INQ_CFG WHERE SQL_ID='050329901';

INSERT INTO "G_INQ_CFG"("CORP_ID", "SQL_ID", "SQL_STRING", "DETAIL_SQL_STRING", "SYSTEM", "REMARKS", "UPD_TIME", "CRT_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('ALL', '050329901', 'SELECT
*
FROM
    SCB_VIPACCT_INFO_TMP
WHERE
1=1
AND upper(VIP_ACTNO)=upper(:"VIP_ACTNO")', NULL, 'CIPS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);



--修改vip维护查询页面的sql-050229801

DELETE FROM G_INQ_CFG WHERE SQL_ID='050229801';

INSERT INTO "G_INQ_CFG"("CORP_ID", "SQL_ID", "SQL_STRING", "DETAIL_SQL_STRING", "SYSTEM", "REMARKS", "UPD_TIME", "CRT_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('SCB', '050229801', 'SELECT
    t.VIP_TYPE,
    t.VIP_ACTNO,
    t.VIP_NAME,
    t.VIP_LEVEL,
    t.REMARKS,
    case t.MOD_STATUS when ''00'' then ''正常'' else ''修改中'' end as MOD_STATUS,
    t.CRT_USER,
    t.CRT_TIME,
    t.UPD_USER,
    t.UPD_TIME,
    t.APV_USER,
    t.APV_TIME
FROM
    SCB_VIPACCT_INFO t
WHERE
    1=1
AND upper(t.VIP_ACTNO)=upper(:"VIP_ACTNO")
', NULL, 'SCB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);-- 服务配置
delete from G_SERVICES where SERVICE_ID in ('CIPS_04499', 'DTT_CAEA_PORT_OUT','DTT_CAEB_PORT_OUT','DTT_CAEA_PORT_IN','DTT_CAEB_PORT_IN','BIZ_CAEA_PORT_OUT','BIZ_CAEB_PORT_OUT','BIZ_CAEA_PORT_IN','BIZ_CAEB_PORT_IN','CIPS_PMTS_DTT_SND','CIPS_PMTS_DTT_RCV','CIPS_PORT_OUT_ROUTE');
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DTT_CAEA_PORT_OUT', 'CIPS', 'PORT_OUT', 'NULL', 'NULL', 'CIPS_OutPort', 'DTT_CAEA_PORT_OUT', 'MQ_OUT', null, null, null, '探测CAE1出口服务', null, '00', null, null, null, 'DTT_CAE1_PORT_OUT', null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DTT_CAEB_PORT_OUT', 'CIPS', 'PORT_OUT', 'NULL', 'NULL', 'CIPS_OutPort', 'DTT_CAEB_PORT_OUT', 'MQ_OUT', null, null, null, '探测CAE2出口服务', null, '00', null, null, null, 'DTT_CAE2_PORT_OUT', null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DTT_CAEA_PORT_IN', 'CIPS', 'PORT_IN', 'NULL', 'NULL', 'CIPS_InPort', 'DTT_CAEA_PORT_IN', 'MQ_IN', null, null, null, '探测CAE1入口服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DTT_CAEB_PORT_IN', 'CIPS', 'PORT_IN', 'NULL', 'NULL', 'CIPS_InPort', 'DTT_CAEB_PORT_IN', 'MQ_IN', null, null, null, '探测CAE2入口服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BIZ_CAEA_PORT_OUT', 'CIPS', 'PORT_OUT', 'NULL', 'NULL', 'CIPS_OutPort', 'BIZ_CAEA_PORT_OUT', 'MQ_OUT', null, null, null, '业务CAE1出口服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BIZ_CAEB_PORT_OUT', 'CIPS', 'PORT_OUT', 'NULL', 'NULL', 'CIPS_OutPort', 'BIZ_CAEB_PORT_OUT', 'MQ_OUT', null, null, null, '业务CAE2出口服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BIZ_CAEA_PORT_IN', 'CIPS', 'PORT_IN', 'NULL', 'NULL', 'CIPS_InPort', 'BIZ_CAEA_PORT_IN', 'MQ_IN', null, null, null, '业务CAE1入口服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('BIZ_CAEB_PORT_IN', 'CIPS', 'PORT_IN', 'NULL', 'NULL', 'CIPS_InPort', 'BIZ_CAEB_PORT_IN', 'MQ_IN', null, null, null, '业务CAE2入口服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_DTT_SND', 'CIPS', null, null, null, 'CIPS_PMTS_DTT_SND', 'CIPS_PMTS_DTT_SND', 'DAEMON', null, null, null, '探测CAE请求发送服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_DTT_RCV', 'CIPS', null, null, null, 'CIPS_PMTS_DTT_RCV', 'CIPS_PMTS_DTT_RCV', 'SERVICE', null, null, null, '探测CAE应答接收服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PORT_OUT_ROUTE', 'CIPS', null, null, null, 'CIPS_PORT_OUT_ROUTE', 'CIPS_PORT_OUT_ROUTE', 'SERVICE', null, null, null, 'CIPS业务报送发送路由服务', null, '00', null, null, null, null, null, null, null, null);
INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_04499', 'CIPS', null, null, null, 'TLR_MADE_MAIN', 'CIPS_HTTP', 'SERVICE', null, null, null, 'PMTS双活管理', null, '00', null, null, null, null, null, null, null, null);


-- 方法配置
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_DTT_RCV', 'CIPS_PMTS_DTT_RCV', 'CIPS', 0, 'libcips_port.so', null, null, '00', null, '20240617163632', '20240617163632', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_DTT_SND', 'CIPS_PMTS_DTT_SND', 'CIPS', 1, 'libcips_port.so', null, null, '00', null, '20240617163632', '20240617163632', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PORT_OUT_ROUTE', 'CIPS_PORT_OUT_ROUTE', 'CIPS', 0, 'libcips_port.so', null, null, '00', null, '20240617163632', '20240617163632', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_DTT_LOG_DELETE', 'DBI_CIPS_PMTS_DTT_LOG_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_DTT_LOG_FIND', 'DBI_CIPS_PMTS_DTT_LOG_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_DTT_LOG_INSERT', 'DBI_CIPS_PMTS_DTT_LOG_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_DTT_LOG_LOCK', 'DBI_CIPS_PMTS_DTT_LOG_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_DTT_LOG_UPDATE', 'DBI_CIPS_PMTS_DTT_LOG_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_DELETE', 'DBI_CIPS_PMTS_NODE_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_FIND', 'DBI_CIPS_PMTS_NODE_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_INSERT', 'DBI_CIPS_PMTS_NODE_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_LOCK', 'DBI_CIPS_PMTS_NODE_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_DELETE', 'DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_DELETE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_FIND', 'DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_FIND', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_INSERT', 'DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_INSERT', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_LOCK', 'DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_LOCK', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_UPDATE', 'DBI_CIPS_PMTS_NODE_STATUS_CHG_LOG_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('DBI_CIPS_PMTS_NODE_UPDATE', 'DBI_CIPS_PMTS_NODE_UPDATE', 'CIPS', 1, 'libcips_dbi.so', null, null, '00', null, '20240617163631', '20240617163631', null, null, null, null, null);
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_04499', 'CIPS_04499', 'CIPS', 1, 'libcips_txn.so', null, null, '00', null, '20240617163632', '20240617163632', null, null, null, null, null);



-- 几个port的MQ参数
delete from G_SPARAS where APP_NAME like '%CAE%';
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEA_PORT_OUT', 'ALL', 'MQ', 'QUEUE', 'Q_DTT_REQ', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEA_PORT_OUT', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEB_PORT_OUT', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEB_PORT_OUT', 'ALL', 'MQ', 'QUEUE', 'Q_DTT_REQ', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEA_PORT_IN', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEA_PORT_IN', 'ALL', 'MQ', 'QUEUE', 'Q_DTT_RSP_GCIPSA', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEB_PORT_IN', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEB_PORT_IN', 'ALL', 'MQ', 'QUEUE', 'Q_DTT_RSP_GCIPSA', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEA_PORT_OUT', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEA_PORT_OUT', 'ALL', 'MQ', 'QUEUE', 'Q_CIPS_CCPC', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEB_PORT_OUT', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEB_PORT_OUT', 'ALL', 'MQ', 'QUEUE', 'Q_CIPS_CCPC', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEA_PORT_IN', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEA_PORT_IN', 'ALL', 'MQ', 'QUEUE', 'Q_CIPS_BANK', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEB_PORT_IN', 'ALL', 'MQ', 'QMGR', 'QMBANK', 'mq队列管理器', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEB_PORT_IN', 'ALL', 'MQ', 'QUEUE', 'Q_CIPS_BANK', '队列', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEA_PORT_OUT', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.42(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEA_PORT_IN', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.42(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEA_PORT_OUT', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.42(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEA_PORT_IN', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.42(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEB_PORT_OUT', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.43(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'DTT_CAEB_PORT_IN', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.43(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEB_PORT_OUT', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.43(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO G_SPARAS (NODE_ID, APP_NAME, CORP_ID, MODULE, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, SYSTEM, EXPIRE, OP_TYPE, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'BIZ_CAEB_PORT_IN', 'ALL', 'MQ', 'MQSERVER', 'GCIPS.SVRCONN/TCP/10.0.6.43(1414)', 'MQSERVER地址', 'NORMAL', '20240709', '00', 'CIPS', 0, null, null, null, null, null, null, null, null, null, null, null, null, null);



-- PMTS相关业务参数
delete from G_PARAS where PARA_KEY in ('PMTS_ROUTE_SWITCH', 'PMTS_DTT_INTERVAL', 'PMTS_DTT_FAIL_TIME', 'PMTS_ROUTE_STRATEGY', 'PMTS_DTT_LOG_RETENTION_DAYS');
INSERT INTO G_PARAS (SYSTEM, CORP_ID, ORG_ID, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, EXPIRE, OP_TYPE, OP_STATUS, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'ALL', 'ALL', 'PMTS_DTT_INTERVAL', '10', '探测时间间隔（秒）', '02', null, '01', null, null, null, 'test', '20240229', '20240229112803', 'test', '20240229', '20240229112803', null, null, null, null, null, null);
INSERT INTO G_PARAS (SYSTEM, CORP_ID, ORG_ID, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, EXPIRE, OP_TYPE, OP_STATUS, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'ALL', 'ALL', 'PMTS_DTT_FAIL_TIME', '120', '多久未响应节点不可用（秒）', '02', null, '01', null, null, null, 'test', '20240229', '20240229112803', 'test', '20240229', '20240229112803', null, null, null, null, null, null);
INSERT INTO G_PARAS (SYSTEM, CORP_ID, ORG_ID, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, EXPIRE, OP_TYPE, OP_STATUS, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'ALL', 'ALL', 'PMTS_ROUTE_STRATEGY', 'RAND', '节点选择策略(RAND-随机，LOAD-低负载）', '02', null, '01', null, null, null, 'test', '20240229', '20240229112803', 'test', '20240229', '20240229112803', null, null, null, null, null, null);
INSERT INTO G_PARAS (SYSTEM, CORP_ID, ORG_ID, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, EXPIRE, OP_TYPE, OP_STATUS, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'ALL', 'ALL', 'PMTS_ROUTE_SWITCH', '1', '是否启用PMTS双活(0-不启用，1-启用）', '02', null, '01', null, null, null, 'test', '20240229', '20240229112803', 'test', '20240229', '20240229112803', null, null, null, null, null, null);
INSERT INTO G_PARAS (SYSTEM, CORP_ID, ORG_ID, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, EXPIRE, OP_TYPE, OP_STATUS, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'ALL', 'ALL', 'PMTS_DTT_LOG_RETENTION_DAYS', '3', '探测历史保留天数', '02', null, '01', null, null, null, 'test', '20240229', '20240229112803', 'test', '20240229', '20240229112803', null, null, null, null, null, null);


-- 初始化PMTS节点表
INSERT INTO CIPS_PMTS_NODE (APP_NODE, APP_SERVER_NAME, SND_QMGR, SND_CHL, PMTS_NODE, PMTS_SERVER_NAME, PMTS_QMGR, DTT_RSP_QUEUE, NODE_STATUS, NODE_LOAD, DTT_PORT_OUT, BIZ_PORT_OUT, START_TIME, LAST_REQ_TIME, LAST_RSP_TIME) VALUES ('SCBLHKHHXXX', 'MBA', 'QMBANK', 'GCIPS.TO.CAE', 'SCBLHKHHXXX', 'CAEA', 'QMUCAEA', 'Q_DTT_RSP_GCIPSA', 'INIT', '0', 'DTT_CAEA_PORT_OUT', 'BIZ_CAEA_PORT_OUT', '20241107165812', '20241107165822', '20240730114109');
INSERT INTO CIPS_PMTS_NODE (APP_NODE, APP_SERVER_NAME, SND_QMGR, SND_CHL, PMTS_NODE, PMTS_SERVER_NAME, PMTS_QMGR, DTT_RSP_QUEUE, NODE_STATUS, NODE_LOAD, DTT_PORT_OUT, BIZ_PORT_OUT, START_TIME, LAST_REQ_TIME, LAST_RSP_TIME) VALUES ('SCBLHKHHXXX', 'MBA', 'QMBANK', 'GCIPS.TO.CAE', 'SCBLHKHHXXX', 'CAEB', 'QMUCAEA', 'Q_DTT_RSP_GCIPSA', 'INIT', '0', 'DTT_CAEB_PORT_OUT', 'BIZ_CAEB_PORT_OUT', '20241107165812', '20241107165822', '20240730114109');



-- 邮件提醒
delete from G_ROUTE where ROUTE_KEY in ('CIPS_PMTS_NODE_ABNORMAL', 'CIPS_PMTS_NODE_RECOVER');
INSERT INTO G_ROUTE (CORP_ID, NODE_ID, ROUTE_ID, ROUTE_KEY, ROUTE_DATA, ROUTE_RESULT, ROUTE_TYPE, ROUTE_MODE, IDX, SYSTEM, REMARKS, STATUS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'ALL', 'GNO_NOTICE', 'CIPS_PMTS_NODE_ABNORMAL', '$(REQ.HEAD.MSG_SENDER)_$(REQ.HEAD.MSG_TYPE)', 'CIPS_PMTS_NODE_ABNORMAL', 'SERVICE', 'R', 4, 'GNOTICE', 'PMTS节点异常提醒', '00', '20140225043400', '20140225043400', null, null, null, null, null);
INSERT INTO G_ROUTE (CORP_ID, NODE_ID, ROUTE_ID, ROUTE_KEY, ROUTE_DATA, ROUTE_RESULT, ROUTE_TYPE, ROUTE_MODE, IDX, SYSTEM, REMARKS, STATUS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'ALL', 'GNO_NOTICE', 'CIPS_PMTS_NODE_RECOVER', '$(REQ.HEAD.MSG_SENDER)_$(REQ.HEAD.MSG_TYPE)', 'CIPS_PMTS_NODE_RECOVER', 'SERVICE', 'R', 4, 'GNOTICE', 'PMTS节点恢复提醒', '00', '20140225043400', '20140225043400', null, null, null, null, null);

delete from GNO_TOPIC where TOPIC in  ('CIPS_PMTS_NODE_ABNORMAL', 'CIPS_PMTS_NODE_RECOVER');
INSERT INTO GNO_TOPIC (TOPIC, TPL_ID, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_NODE_ABNORMAL', 'CIPS_PMTS_NODE_ABNORMAL', 'PMTS节点异常提醒', '20240709', '20240709', null, null, null, null, null);
INSERT INTO GNO_TOPIC (TOPIC, TPL_ID, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_NODE_RECOVER', 'CIPS_PMTS_NODE_RECOVER', 'PMTS节点恢复提醒', '20240709', '20240709', null, null, null, null, null);


delete from GNO_TPL where TPL_ID in  ('CIPS_PMTS_NODE_ABNORMAL', 'CIPS_PMTS_NODE_RECOVER');
INSERT INTO GNO_TPL (TPL_ID, TPL_LANG, CHL_ID, MSG_FMT, MSG_TITLE, TPL_DATA, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_NODE_ABNORMAL', 'cn', 'EMAIL', 'text', 'PMTS节点异常提醒', '应用节点[$(DATA.IN.APP_SERVER_NAME)]到PMTS节点[$(DATA.IN.PMTS_SERVER_NAME)]的探测异常', 'PMTS节点异常提醒', '20240709      ', null, null, null, null, null, null);
INSERT INTO GNO_TPL (TPL_ID, TPL_LANG, CHL_ID, MSG_FMT, MSG_TITLE, TPL_DATA, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('CIPS_PMTS_NODE_RECOVER', 'cn', 'EMAIL', 'text', 'PMTS节点恢复提醒', '应用节点[$(DATA.IN.APP_SERVER_NAME)]到PMTS节点[$(DATA.IN.PMTS_SERVER_NAME)]的探测恢复', 'PMTS节点恢复提醒', '20240709      ', null, null, null, null, null, null);


-- 菜单
delete from GTLR_MENU where MENU_ID in ('m-504499', 'm-05pmts');
INSERT INTO GTLR_MENU (CORP_ID, MENU_ID, PAR_MENU_ID, TXNO, MENU_NAME, MENU_ICON, VIEW_NAME, SYS_CODE, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('TESTCORP', 'm-504499', 'm-05pmts', '0449', '504499-PMTS双活管理', 'silk/application_view_list.png', 'Page0504499Cust', 'CIPS', null, null, null, null, null);
INSERT INTO GTLR_MENU (CORP_ID, MENU_ID, PAR_MENU_ID, TXNO, MENU_NAME, MENU_ICON, VIEW_NAME, SYS_CODE, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('TESTCORP', 'm-05pmts', 'm-root', null, 'PMTS管理', 'silk/application_cascade.png', 'null', 'CIPS', null, null, null, null, null);


-- 页面查询SQL
delete from G_INQ_CFG where SQL_ID in ('050449901', '050449902', '050449903', '050449904');
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449901', 'select (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_DTT_INTERVAL'' )    as PMTS_DTT_INTERVAL,
       (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_DTT_FAIL_TIME'' )   as PMTS_DTT_FAIL_TIME,
       (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_ROUTE_STRATEGY'' )  as PMTS_ROUTE_STRATEGY,
       (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_DTT_LOG_RETENTION_DAYS'' ) as PMTS_DTT_LOG_RETENTION_DAYS
from dual', null, 'CIPS', null, null, null, null, null, null, null, null);
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449902', 'select * from cips_pmts_node order by APP_SERVER_NAME, PMTS_SERVER_NAME', null, 'CIPS', null, null, null, null, null, null, null, null);
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449903', 'select *
from CIPS_PMTS_DTT_LOG
where APP_SERVER_NAME = :"APP_SERVER_NAME"
  and PMTS_SERVER_NAME = :"PMTS_SERVER_NAME"
  and DTT_REQ_SND_TIME >= :"BEGIN_TIME"
  and DTT_REQ_SND_TIME <= :"END_TIME"
  order by DTT_REQ_SND_TIME desc', null, 'CIPS', null, null, null, null, null, null, null, null);
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449904', 'select *
from CIPS_PMTS_NODE_STATUS_CHG_LOG
where APP_SERVER_NAME = :"APP_SERVER_NAME"
  and PMTS_SERVER_NAME = :"PMTS_SERVER_NAME"
  and STATUS_CHG_TIME >= :"BEGIN_TIME"
  and STATUS_CHG_TIME <= :"END_TIME"
  order by STATUS_CHG_TIME desc', null, 'CIPS', null, null, null, null, null, null, null, null);


-- 字典
delete from  GPAY_BASE_DIC where GROUP_ID in ('050124_0000', '050125_0000');
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050125_0000', 4, 'PMTS节点选择策略', 'RAND', '随机选择', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050125_0000', 4, 'PMTS节点选择策略', 'LOAD', '选择低负载', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 1, 'PMTS节点探测状态', 'INIT', '启动中', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 2, 'PMTS节点探测状态', 'NORM', '正常', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 3, 'PMTS节点探测状态', 'CLSD', '关闭', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 4, 'PMTS节点探测状态', 'EXCP', '异常', null, null, null, null, null);

delete from G_FUNS where FUN_ID in ('CIPS_382_RCV', 'CIPS_108_RCV', 'CIPS_108_RCV_NOTICE', 'CIPS_10801', 'SCB_CIPS_PDNG_NOTICE');
delete from G_SERVICES where SERVICE_ID in ('CIPS_10801', 'SCB_CIPS_PDNG_NOTICE');

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_382_RCV', 'CIPS_382_RCV', 'CIPS', 0, 'libcips_rcv.so', null, null, '00', null, '20230714100654', '20230714100654', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_108_RCV', 'CIPS_108_RCV', 'CIPS', 0, 'libcips_rcv.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_108_RCV_NOTICE', 'CIPS_108_RCV_NOTICE', 'CIPS', 0, 'libcips_notice.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_10801', 'CIPS_10801', 'CIPS', 1, 'libcips_txn.so', null, null, '00', null, '20231017144705', '20231017144705', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB_CIPS_PDNG_NOTICE', 'SCB', null, 'libscb_notice.so', null, null, '00', null, '2024017164700', '2024017164700', null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_10801', 'CIPS', null, null, null, 'CIPS_MADE_MAIN', 'CIPS_HTTP', 'SERVICE', null, null, null, '费用扣款通知录入', null, '00', null, null, null, null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB', null, null, null, 'SCB_CIPS_PDNG_NOTICE', 'DEFAULT', 'SERVICE', null, null, null, '检查清算排队数据提醒函数', null, '00', 0, null, null, null, null, null, null, null);