------------------------------------------
-- 每隔30分钟发送清算排队业务信息通知
------------------------------------------
--定时任务部分
INSERT INTO G_LOOP_CALL (NODE_ID, CORP_ID, CALL_ID, SYSTEM, CALL_DESC, CALL_SERVICE, CALL_REQ, START_TIME, END_TIME, INTERVAL_TIME, NEXT_TIME, STATUS, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('DEV', 'SCB', 'SCB_CIPS_PDNG_NOTICE', 'CIPS', '定时发送清算排队邮件', 'SCB_CIPS_PDNG_NOTICE', '{"CORP_ID": "SCB"}', '000000', '240000', 1800, '20260312153556', '1', null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB', null, null, null, 'SCB_CIPS_PDNG_NOTICE', 'DEFAULT', 'SERVICE', null, null, null, '检查清算排队数据提醒函数', null, '00', 0, null, null, null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB_CIPS_PDNG_NOTICE', 'SCB', null, 'libscb_notice.so', null, null, '00', null, '2024017164700', '2024017164700', null, null, null, null, null);

--邮件部分
INSERT INTO GNO_TPL (TPL_ID, TPL_LANG, CHL_ID, MSG_FMT, MSG_TITLE, TPL_DATA, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, MOD_STATUS, SEQ_NO) VALUES ('SCB_QUEUESETTLE_PDNG', 'cn', 'EMAIL', 'text', 'SCB_QUEUESETTLE_PDNG', '检查清算排队数据提醒

排队数量：$(DATA.IN.PDNG_COUNT)
排队内容：
$(DATA.IN.CONTENT)', '检查清算排队数据提醒函数', '20240618114217', '20240617165145', null, null, null, null, null, 'test', '20240617', 'test', '20240618', 'test', '20240618', '20240618114226', '00', '20240618000000843215');

INSERT INTO GNO_TOPIC (TOPIC, TPL_ID, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, MOD_STATUS, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, SEQ_NO)
VALUES ('SCB_QUEUESETTLE_PDNG', 'SCB_QUEUESETTLE_PDNG', '清算排队提醒函数', null, '20240618113807', null, null, null, null, null, '00', 'test', '20240618', null, null, 'test', '20240618', '20240618113817', null);

INSERT INTO G_ROUTE (CORP_ID, NODE_ID, ROUTE_ID, ROUTE_KEY, ROUTE_DATA, ROUTE_RESULT, ROUTE_TYPE, ROUTE_MODE, IDX, SYSTEM, REMARKS, STATUS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('ALL', 'ALL', 'GNO_NOTICE', 'SCB_QUEUESETTLE_PDNG', '$(REQ.HEAD.MSG_SENDER)_$(REQ.HEAD.MSG_TYPE)', 'SCB_QUEUESETTLE_PDNG', 'SERVICE', 'R', 4, 'GNOTICE', '检查清算排队数据提醒', '00', '20240617163000', '20240617163000', null, null, null, null, null);


------------------------------------------
-- 自动发起（T-1）日索费信息提醒
------------------------------------------
-- 定时任务部分
INSERT INTO G_LOOP_CALL (NODE_ID, CORP_ID, CALL_ID, SYSTEM, CALL_DESC, CALL_SERVICE, CALL_REQ, START_TIME, END_TIME, INTERVAL_TIME, NEXT_TIME, STATUS, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('DEV', 'SCB', 'SCB_CIPS_CHARGES_AUTO_NOTICE', 'CIPS', '自动发起（T-1）日索费信息提醒', 'SCB_CIPS_CHARGES_AUTO_NOTICE', '{"CORP_ID": "SCB", "SYSTEM": "SCB"}', '090000', '100000', 86400, '20260313090000', '1', null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_CHARGES_AUTO_NOTICE', 'SCB', null, 'NULL', 'NULL', 'SCB_CIPS_CHARGES_AUTO_NOTICE', 'DEFAULT', 'SERVICE', null, null, null, '发送索费信息邮件通知', null, '00', null, null, null, null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_CHARGES_AUTO_NOTICE', 'SCB_CIPS_CHARGES_AUTO_NOTICE', 'SCB', 1, 'libscb_task.so', null, null, '00', null, '20230922094702', '20230922094702', null, null, null, null, null);

--邮件部分
INSERT INTO GNO_TPL (TPL_ID, TPL_LANG, CHL_ID, MSG_FMT, MSG_TITLE, TPL_DATA, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, MOD_STATUS, SEQ_NO) VALUES ('SCB_109_INFORMATION_RCV', 'cn', 'EMAIL', 'text', '索费往账信息提醒', '索费往账信息提醒

数据统计日期：$(DATA.IN.WORK_DATE)
索费总笔数：$(DATA.IN.TOTAL_COUNT)
索费未收款金额：$(DATA.IN.CTRL_SUM_AMT) 元
索费付款金额：$(DATA.IN.RECEIPT_AMT) 元', null, '20230925170331', '20230925154237', null, null, null, null, null, 'test', '20230925', 'test', '20230925', 'test', '20230925', '20230925170345', '00', '20230928000000743320');

INSERT INTO GNO_TOPIC (TOPIC, TPL_ID, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5, MOD_STATUS, CRT_USER, CRT_DATE, UPD_USER, UPD_DATE, APV_USER, APV_DATE, APV_TIME, SEQ_NO)
VALUES ('SCB_QUEUESETTLE_PDNG', 'SCB_QUEUESETTLE_PDNG', '清算排队提醒函数', null, '20240618113807', null, null, null, null, null, '00', 'test', '20240618', null, null, 'test', '20240618', '20240618113817', null);

INSERT INTO G_ROUTE (CORP_ID, NODE_ID, ROUTE_ID, ROUTE_KEY, ROUTE_DATA, ROUTE_RESULT, ROUTE_TYPE, ROUTE_MODE, IDX, SYSTEM, REMARKS, STATUS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('ALL', 'ALL', 'GNO_NOTICE', 'SCB_QUEUESETTLE_PDNG', '$(REQ.HEAD.MSG_SENDER)_$(REQ.HEAD.MSG_TYPE)', 'SCB_QUEUESETTLE_PDNG', 'SERVICE', 'R', 4, 'GNOTICE', '检查清算排队数据提醒', '00', '20240617163000', '20240617163000', null, null, null, null, null);
