-- CIPS_902_LIST,CIPS_AUTH 两张表增加 CCY CHAR(3)
ALTER TABLE CIPS_902_LIST ADD CCY CHAR(3);
ALTER TABLE CIPS_AUTH ADD CCY CHAR(3);

COMMENT ON COLUMN CIPS_902_LIST.CCY IS '币种';
COMMENT ON COLUMN CIPS_AUTH.CCY IS '币种'

--报文发送时间扩长
ALTER TABLE CIPS_111 MODIFY CRE_DT_TM CHAR(29);
ALTER TABLE CIPS_112 MODIFY CRE_DT_TM CHAR(29);