--业务权限表
update CIPS_AUTH set  CCY = 'CNY' where 1=1;
--DBI.SQL
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_CHRG_LIST_DELETE';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_CHRG_LIST_DELETE', 'DBI_CIPS_111_CHRG_LIST_DELETE', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_CHRG_LIST_FIND';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_CHRG_LIST_FIND', 'DBI_CIPS_111_CHRG_LIST_FIND', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_CHRG_LIST_INSERT';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_CHRG_LIST_INSERT', 'DBI_CIPS_111_CHRG_LIST_INSERT', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_CHRG_LIST_LOCK';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_CHRG_LIST_LOCK', 'DBI_CIPS_111_CHRG_LIST_LOCK', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_CHRG_LIST_UPDATE';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_CHRG_LIST_UPDATE', 'DBI_CIPS_111_CHRG_LIST_UPDATE', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_REG_LIST_DELETE';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_REG_LIST_DELETE', 'DBI_CIPS_111_REG_LIST_DELETE', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_REG_LIST_FIND';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_REG_LIST_FIND', 'DBI_CIPS_111_REG_LIST_FIND', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_REG_LIST_INSERT';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_REG_LIST_INSERT', 'DBI_CIPS_111_REG_LIST_INSERT', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_REG_LIST_LOCK';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_REG_LIST_LOCK', 'DBI_CIPS_111_REG_LIST_LOCK', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_111_REG_LIST_UPDATE';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_111_REG_LIST_UPDATE', 'DBI_CIPS_111_REG_LIST_UPDATE', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_112_COV_DELETE';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_112_COV_DELETE', 'DBI_CIPS_112_COV_DELETE', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_112_COV_FIND';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_112_COV_FIND', 'DBI_CIPS_112_COV_FIND', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_112_COV_INSERT';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_112_COV_INSERT', 'DBI_CIPS_112_COV_INSERT', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
delete from G_FUNS where FUN_ID = 'DBI_CIPS_112_COV_LOCK';
INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES('DBI_CIPS_112_COV_LOCK', 'DBI_CIPS_112_COV_LOCK', 'CIPS', 1, 'libcips_dbi.so', NULL, NULL, '00', NULL, '20251125172254', '20251125172254', NULL, NULL, NULL, NULL, NULL);
COMMIT;
--来账补充录入查询SQL：CIPS114.ORI_MSG_TYPE-->CIPS114.ORGNL_MSG_NM_ID
DELETE from G_INQ_CFG where SQL_ID = '050139801';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ANZ', '050139801', 'SELECT
	a.txn_seq_no,
	a.msg_no,
	a.center_date,
	a.txn_dir,
	a.msg_id,
	a.amt,
	a.pboc_status,
	a.comm_status,
	a.payer_actno,
	a.payer_name,
	a.payee_actno,
	a.payee_name,
	a.snd_st_brno AS op_st_brno,
	a.snd_st_brname AS op_st_brname
FROM
	cips_txn a
	LEFT JOIN CIPS_114 b ON a.TXN_SEQ_NO=b.TXN_SEQ_NO
WHERE
	a.txn_dir = ''2''
	AND (a.msg_no = ''111'' OR ( a.MSG_NO = ''114'' AND b.ORGNL_MSG_NM_ID IN (''cips.111.001.01'', ''cips.111.001.02'')))
	AND a.NEXT_FLOW = ''S50''
	AND a.MSG_ID = : "MSG_ID"
	AND a.AMT >= : "START_AMT"
	AND a.AMT <= : "END_AMT"
	AND a.ORG_ID = : "HEAD.ORG_ID"
	AND ( ( ''0'' = : "IS_VIP" ) OR ( ''1'' = : "IS_VIP" AND a.IS_VIP = : "IS_VIP" ) )
	AND a.TXN_SEQ_NO LIKE ''%'' ||: "TXN_SEQ_NO" || ''%''
ORDER BY
	a.txn_seq_no DESC', null, 'CIPS', null, null, null, null, null, null, null, null);
COMMIT;
--来账补充审核
DELETE from G_INQ_CFG where SQL_ID = '050149801';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ANZ', '050149801', 'SELECT
	a.TXN_SEQ_NO,
	a.MSG_NO,
	a.CENTER_DATE,
	a.TXN_DIR,
	a.MSG_ID,
	a.AMT,
	a.PBOC_STATUS,
	a.COMM_STATUS,
	a.PAYER_ACTNO,
	a.PAYER_NAME,
	a.PAYEE_ACTNO,
	a.PAYEE_NAME,
	a.SND_ST_BRNO AS OP_ST_BRNO,
	a.SND_ST_BRNAME AS OP_ST_BRNAME,
	a.ORG_ID,
	a.TXN_STATUS,
	a.MADE_USER 
FROM
	CIPS_TXN a
	LEFT JOIN CIPS_114 b ON a.TXN_SEQ_NO=b.TXN_SEQ_NO
WHERE
	a.TXN_DIR = ''2'' 
	AND (a.msg_no = ''111'' OR ( a.MSG_NO = ''114'' AND b.ORGNL_MSG_NM_ID IN (''cips.111.001.02'', ''cips.111.001.02'')))
	AND a.NEXT_FLOW IN ( ''S19'' ) 
	AND a.MSG_ID = : "MSG_ID" 
	AND a.AMT >= : "START_AMT" 
	AND a.AMT <= : "END_AMT" 
	AND a.ORG_ID = : "ORG_ID" 
	AND a.TXN_STATUS =: "TXN_STATUS" 
	AND a.MADE_USER <>: "HEAD.USER_ID" 
	AND a.TXN_SEQ_NO LIKE ''%'' ||: "TXN_SEQ_NO" || ''%'' 
ORDER BY
	a.TXN_SEQ_NO DESC', null, 'CIPS', null, null, null, null, null, null, null, null);
COMMIT;
--来账补充授权
DELETE from G_INQ_CFG where SQL_ID = '050179801';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ANZ', '050179801', 'SELECT
	a.TXN_SEQ_NO,
	a.MSG_NO,
	a.CENTER_DATE,
	a.TXN_DIR,
	a.MSG_ID,
	a.AMT,
	a.PBOC_STATUS,
	a.COMM_STATUS,
	a.PAYER_ACTNO,
	a.PAYER_NAME,
	a.PAYEE_ACTNO,
	a.PAYEE_NAME,
	a.SND_ST_BRNO AS OP_ST_BRNO,
	a.SND_ST_BRNAME AS OP_ST_BRNAME,
	a.ORG_ID,
	a.TXN_STATUS,
	a.MADE_USER,
	a.CHK_USER 
FROM
	CIPS_TXN a 
	LEFT JOIN CIPS_114 b ON a.TXN_SEQ_NO=b.TXN_SEQ_NO
WHERE
	a.TXN_DIR = ''2'' 
	AND (a.msg_no = ''111'' OR ( a.MSG_NO = ''114'' AND b.ORGNL_MSG_NM_ID IN (''cips.111.001.02'', ''cips.111.001.02'')))
	AND a.NEXT_FLOW IN ( ''S53'' ) 
	AND a.MSG_ID = : "MSG_ID" 
	AND a.AMT >= : "START_AMT" 
	AND a.AMT <= : "END_AMT" 
	AND a.ORG_ID = : "ORG_ID" 
	AND a.TXN_STATUS =: "TXN_STATUS" 
	AND a.MADE_USER <>: "HEAD.USER_ID" 
	AND ( a.CHK_USER <> : "HEAD.USER_ID" OR a.CHK_USER IS NULL ) 
	AND a.TXN_SEQ_NO LIKE ''%'' ||: "TXN_SEQ_NO" || ''%'' 
ORDER BY
	a.TXN_SEQ_NO DESC', null, 'CIPS', null, null, null, null, null, null, null, null);
	COMMIT;
--数据字典
delete from GPAY_BASE_DIC where GROUP_ID = '050129_0000';
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5, DATA_DESC_EN) VALUES ('05', '0000', '050129_0000', 2, '收费方式111/113', 'CRED', '贷方承担', null, null, null, null, null, 'Settled through a clearing system');
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5, DATA_DESC_EN) VALUES ('05', '0000', '050129_0000', 1, '收费方式111/113', 'DEBT', '借方承担', null, null, null, null, null, 'Settled through a clearing system');
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5, DATA_DESC_EN) VALUES ('05', '0000', '050129_0000', 3, '收费方式111/113', 'SHAR', '共同承担', null, null, null, null, null, 'Settled through a clearing system');
commit;
--录入提示银行间结算日期报错
delete FROM G_VALID WHERE VALID_TAG = 'INTR_BK_STTLM_DT';
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11101', 10019, 'INTR_BK_STTLM_DT', '银行间结算日期', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11102', 10019, 'INTR_BK_STTLM_DT', '银行间结算日期', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11401', 10020, 'INTR_BK_STTLM_DT', '银行间结算日期', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11402', 10020, 'INTR_BK_STTLM_DT', '银行间结算日期', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11202', 10019, 'INTR_BK_STTLM_DT', '银行间结算日期', 'O', null, 8, 'D', null, null, null, null, null, null, null);
commit;

delete from G_VALID where VALID_TAG = 'INTR_DATE';
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11301', 40, 'INTR_DATE', '起息日', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11302', 40, 'INTR_DATE', '起息日', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11201', 330, 'INTR_DATE', '起息日', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_13301', 33, 'INTR_DATE', '起息日', 'O', null, 8, 'D', null, null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_13302', 33, 'INTR_DATE', '起息日', 'O', null, 8, 'D', null, null, null, null, null, null, null);


delete from G_VALID where VALID_TAG = 'BIZ_PRIO';
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11301', 50, 'BIZ_PRIO', '业务优先级', 'O', null, 4, 'S', 'A', null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11302', 50, 'BIZ_PRIO', '业务优先级', 'O', null, 4, 'S', 'A', null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_11201', 350, 'BIZ_PRIO', '业务优先级', 'O', null, 4, 'S', 'AN', null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_13301', 35, 'BIZ_PRIO', '业务优先级', 'O', null, 4, 'S', 'A', null, null, null, null, null, null);
INSERT INTO CIPS_ANZ.G_VALID (SYSTEM, VALID_ID, VALID_INDEX, VALID_TAG, VALID_NAME, VALID_REQUIRED, VALID_LENGTH, VALID_C_LENGTH, VALID_TYPE, VALID_OPTION, RSV1, RSV2, RSV3, RSV4, RSV5, VALID_FILTER) VALUES ('CIPS', 'CIPS_13302', 35, 'BIZ_PRIO', '业务优先级', 'O', null, 4, 'S', 'A', null, null, null, null, null, null);
commit;

--退汇复核的查询
DELETE from G_INQ_CFG where SQL_ID = '051140301';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '051140301', 'SELECT a.txn_seq_no,
       b.seq_no,
       a.msg_no,
       a.work_date,
       a.txn_dir,
       a.msg_id,
       a.pboc_status,
       a.comm_status,
       a.payer_actno,
       a.payer_name,
       a.payee_actno,
       a.payee_name,
       CASE WHEN a.txn_dir = ''1'' THEN a.rcv_st_brno ELSE a.snd_st_brno END     AS op_st_brno,
       CASE WHEN a.txn_dir = ''1'' THEN a.rcv_st_brname ELSE a.snd_st_brname END AS op_st_brname,
       b.RTRD_INSTD_AMT as AMT,
       b.ORGNL_MSG_NM_ID,
       b.ORGNL_MSG_ID
FROM cips_txn a left join cips_114 b
on a.SEQ_NO=b.SEQ_NO
WHERE a.msg_no = ''114''
  AND a.next_flow = ''S01''
  AND a.TXN_DIR = ''1''
  AND a.WORK_DATE = :"WORK_DATE"
  AND a.TXN_SEQ_NO = :"TXN_SEQ_NO"
  AND a.AMT >= :"START_AMT"
  AND a.AMT <= :"END_AMT"
  AND a.ORG_ID = :"HEAD.ORG_ID"
  AND b.ORGNL_MSG_ID = :"ORGNL_MSG_ID"
order by a.TXN_SEQ_NO desc', null, 'CIPS', null, null, null, null, null, null, null, null);
COMMIT;
--退汇授权的查询
DELETE from G_INQ_CFG where SQL_ID = '051140701';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '051140701', 'SELECT a.txn_seq_no,
       b.seq_no,
       a.msg_no,
       a.work_date,
       a.txn_dir,
       a.msg_id,
       a.pboc_status,
       a.comm_status,
       a.payer_actno,
       a.payer_name,
       a.payee_actno,
       a.payee_name,
       CASE WHEN a.txn_dir = ''1'' THEN a.rcv_st_brno ELSE a.snd_st_brno END     AS op_st_brno,
       CASE WHEN a.txn_dir = ''1'' THEN a.rcv_st_brname ELSE a.snd_st_brname END AS op_st_brname,
       b.AMT,
       b.ORGNL_MSG_NM_ID,
       b.ORGNL_MSG_ID
FROM cips_txn a left join cips_114 b
on a.SEQ_NO=b.SEQ_NO
WHERE a.msg_no = ''114''
  AND a.next_flow = ''S03''
  AND a.TXN_DIR = ''1''
  AND a.WORK_DATE = :"WORK_DATE"
  AND a.TXN_SEQ_NO = :"TXN_SEQ_NO"
  AND a.AMT >= :"START_AMT"
  AND a.AMT <= :"END_AMT"
  AND a.ORG_ID = :"HEAD.ORG_ID"
  AND b.ORGNL_MSG_ID = :"ORGNL_MSG_ID"
order by a.TXN_SEQ_NO desc', null, 'CIPS', null, null, null, null, null, null, null, null);
COMMIT;
--退汇修改的查询
DELETE from G_INQ_CFG where SQL_ID = '051140201';
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '051140201', 'SELECT a.txn_seq_no,
       b.seq_no,
       a.msg_no,
       a.work_date,
       a.txn_dir,
       a.msg_id,
       a.pboc_status,
       a.comm_status,
       a.payer_actno,
       a.payer_name,
       a.payee_actno,
       a.payee_name,
       CASE WHEN a.txn_dir = ''1'' THEN a.rcv_st_brno ELSE a.snd_st_brno END     AS op_st_brno,
       CASE WHEN a.txn_dir = ''1'' THEN a.rcv_st_brname ELSE a.snd_st_brname END AS op_st_brname,
       b.RTRD_INSTD_AMT as AMT,
       b.ORGNL_MSG_NM_ID,
       b.ORGNL_MSG_ID
FROM cips_txn a left join cips_114 b
on a.SEQ_NO=b.SEQ_NO
WHERE a.msg_no = ''114''
  AND a.next_flow = ''S30''
  AND a.WORK_DATE = :"WORK_DATE"
  AND a.TXN_SEQ_NO = :"TXN_SEQ_NO"
  AND a.MADE_USER = :"MADE_USER"
  AND a.TXN_DIR = ''1''
  AND a.AMT >= :"START_AMT"
  AND a.AMT <= :"END_AMT"
  AND a.TXN_STATUS = :"TXN_STATUS"
  AND a.ORG_ID = :"HEAD.ORG_ID"
  AND b.ORGNL_MSG_ID = :"ORGNL_MSG_ID"
order by a.TXN_SEQ_NO desc', null, 'CIPS', null, null, null, null, null, null, null, null);
COMMIT;
