DELETE FROM GTLR_CHECK_CFG WHERE CHECK_ID='CIPS_11403' AND TAG_NAME='ORGNL_MSG_ID';
INSERT INTO GTLR_CHECK_CFG (CHECK_ID,CHECK_INDEX,CORP_ID,SYSTEM,TAG_NAME,TAG_DESC,TABLE_NAME,COLUMN_NAME,KEY_NAME,RSV1,RSV2,RSV3,RSV4,RSV5) VALUES ('CIPS_11403',0,'SCB','CIPS','ORGNL_MSG_ID','原报文标识号','CIPS_114',null,'SEQ_NO',null,null,null,null,null);
