-- 菜单
delete from GTLR_MENU where MENU_ID in ('m-504499', 'm-05pmts');
INSERT INTO GTLR_MENU (CORP_ID, MENU_ID, PAR_MENU_ID, TXNO, MENU_NAME, MENU_ICON, VIEW_NAME, SYS_CODE, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('TESTCORP', 'm-504499', 'm-05pmts', '0449', '504499-PMTS双活管理', 'silk/application_view_list.png', 'Page0504499Cust', 'CIPS', null, null, null, null, null);
INSERT INTO GTLR_MENU (CORP_ID, MENU_ID, PAR_MENU_ID, TXNO, MENU_NAME, MENU_ICON, VIEW_NAME, SYS_CODE, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('TESTCORP', 'm-05pmts', 'm-root', null, 'PMTS管理', 'silk/application_cascade.png', 'null', 'CIPS', null, null, null, null, null);


-- 页面查询SQL
delete from G_INQ_CFG where SQL_ID in ('050449901', '050449902', '050449903', '050449904');
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449901', 'select (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_DTT_INTERVAL'' )    as PMTS_DTT_INTERVAL,
       (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_DTT_FAIL_TIME'' )   as PMTS_DTT_FAIL_TIME,
       (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_ROUTE_STRATEGY'' )  as PMTS_ROUTE_STRATEGY,
       (select PARA_VALUE from G_PARAS where PARA_KEY = ''PMTS_DTT_LOG_RETENTION_DAYS'' ) as PMTS_DTT_LOG_RETENTION_DAYS
from dual', null, 'CIPS', null, null, null, null, null, null, null, null);
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449902', 'select * from cips_pmts_node order by APP_SERVER_NAME, PMTS_SERVER_NAME', null, 'CIPS', null, null, null, null, null, null, null, null);
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449903', 'select *
from CIPS_PMTS_DTT_LOG
where APP_SERVER_NAME = :"APP_SERVER_NAME"
  and PMTS_SERVER_NAME = :"PMTS_SERVER_NAME"
  and DTT_REQ_SND_TIME >= :"BEGIN_TIME"
  and DTT_REQ_SND_TIME <= :"END_TIME"
  order by DTT_REQ_SND_TIME desc', null, 'CIPS', null, null, null, null, null, null, null, null);
INSERT INTO G_INQ_CFG (CORP_ID, SQL_ID, SQL_STRING, DETAIL_SQL_STRING, SYSTEM, REMARKS, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', '050449904', 'select *
from CIPS_PMTS_NODE_STATUS_CHG_LOG
where APP_SERVER_NAME = :"APP_SERVER_NAME"
  and PMTS_SERVER_NAME = :"PMTS_SERVER_NAME"
  and STATUS_CHG_TIME >= :"BEGIN_TIME"
  and STATUS_CHG_TIME <= :"END_TIME"
  order by STATUS_CHG_TIME desc', null, 'CIPS', null, null, null, null, null, null, null, null);


-- 字典
delete from  GPAY_BASE_DIC where GROUP_ID in ('050124_0000', '050125_0000');
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050125_0000', 4, 'PMTS节点选择策略', 'RAND', '随机选择', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050125_0000', 4, 'PMTS节点选择策略', 'LOAD', '选择低负载', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 1, 'PMTS节点探测状态', 'INIT', '启动中', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 2, 'PMTS节点探测状态', 'NORM', '正常', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 3, 'PMTS节点探测状态', 'CLSD', '关闭', null, null, null, null, null);
INSERT INTO GPAY_BASE_DIC (SYS_ID, CORP_ID, GROUP_ID, DATA_SORT_ID, GROUP_DESC, DATA_VALUE, DATA_DESC, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('05', '0000', '050124_0000', 4, 'PMTS节点探测状态', 'EXCP', '异常', null, null, null, null, null);

