--增添vip数据字典
INSERT INTO "GPAY_BASE_DIC"("SYS_ID", "CORP_ID", "GROUP_ID", "DATA_SORT_ID", "GROUP_DESC", "DATA_VALUE", "DATA_DESC", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('05', '0000', 'VIP_0000', '1', 'VIP账户类型', '1', 'Customer_Account', NULL, NULL, NULL, NULL, NULL);

INSERT INTO "GPAY_BASE_DIC"("SYS_ID", "CORP_ID", "GROUP_ID", "DATA_SORT_ID", "GROUP_DESC", "DATA_VALUE", "DATA_DESC", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('05', '0000', 'VIP_0000', '2', 'VIP账户类型', '2', 'BIC_Code', NULL, NULL, NULL, NULL, NULL);

--新增参数
INSERT INTO G_PARAS (SYSTEM, CORP_ID, ORG_ID, PARA_KEY, PARA_VALUE, REMARKS, PARA_TYPE, PARA_VER, STATUS, EXPIRE, OP_TYPE, OP_STATUS, UPT_USER, UPT_DATE, UPT_TIME, CHECK_USER, CHECK_DATE, CHECK_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5) VALUES ('ALL', 'SCB', 'ALL', 'SCB_HK_VIP_SWITCH', 'on', 'on(使用HK的VIP逻辑)，off(使用CN的VIP逻辑)', '02', null, '00', null, null, null, null, null, null, 'dydy', '20260311', '20260311174056', null, null, null, null, null, null);

--修改vip维护页面的sql-050319901

DELETE FROM G_INQ_CFG WHERE SQL_ID='050319901';

INSERT INTO "G_INQ_CFG"("CORP_ID", "SQL_ID", "SQL_STRING", "DETAIL_SQL_STRING", "SYSTEM", "REMARKS", "UPD_TIME", "CRT_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('SCB', '050319901', 'SELECT
    t.VIP_TYPE,
    t.VIP_ACTNO,
    t.VIP_NAME,
    t.VIP_LEVEL,
	t.REMARKS,
	t.CRT_TIME,
	t.UPD_TIME
FROM
    SCB_VIPACCT_INFO t
WHERE
    1=1
AND VIP_TYPE=:"VIP_TYPE"
AND upper(VIP_ACTNO)=upper(:"VIP_ACTNO")
AND VIP_NAME=:"VIP_NAME"
AND VIP_LEVEL=:"VIP_LEVEL"', NULL, 'SCB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--修改vip维护审核页面的sql-050329901

DELETE FROM G_INQ_CFG WHERE SQL_ID='050329901';

INSERT INTO "G_INQ_CFG"("CORP_ID", "SQL_ID", "SQL_STRING", "DETAIL_SQL_STRING", "SYSTEM", "REMARKS", "UPD_TIME", "CRT_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('ALL', '050329901', 'SELECT
*
FROM
    SCB_VIPACCT_INFO_TMP
WHERE
1=1
AND upper(VIP_ACTNO)=upper(:"VIP_ACTNO")', NULL, 'CIPS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);



--修改vip维护查询页面的sql-050229801

DELETE FROM G_INQ_CFG WHERE SQL_ID='050229801';

INSERT INTO "G_INQ_CFG"("CORP_ID", "SQL_ID", "SQL_STRING", "DETAIL_SQL_STRING", "SYSTEM", "REMARKS", "UPD_TIME", "CRT_TIME", "RSV1", "RSV2", "RSV3", "RSV4", "RSV5") VALUES ('SCB', '050229801', 'SELECT
    t.VIP_TYPE,
    t.VIP_ACTNO,
    t.VIP_NAME,
    t.VIP_LEVEL,
    t.REMARKS,
    case t.MOD_STATUS when ''00'' then ''正常'' else ''修改中'' end as MOD_STATUS,
    t.CRT_USER,
    t.CRT_TIME,
    t.UPD_USER,
    t.UPD_TIME,
    t.APV_USER,
    t.APV_TIME
FROM
    SCB_VIPACCT_INFO t
WHERE
    1=1
AND upper(t.VIP_ACTNO)=upper(:"VIP_ACTNO")
', NULL, 'SCB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);