delete from G_FUNS where FUN_ID in ('CIPS_382_RCV', 'CIPS_108_RCV', 'CIPS_108_RCV_NOTICE', 'CIPS_10801', 'SCB_CIPS_PDNG_NOTICE');
delete from G_SERVICES where SERVICE_ID in ('CIPS_10801', 'SCB_CIPS_PDNG_NOTICE');

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_382_RCV', 'CIPS_382_RCV', 'CIPS', 0, 'libcips_rcv.so', null, null, '00', null, '20230714100654', '20230714100654', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_108_RCV', 'CIPS_108_RCV', 'CIPS', 0, 'libcips_rcv.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_108_RCV_NOTICE', 'CIPS_108_RCV_NOTICE', 'CIPS', 0, 'libcips_notice.so', null, null, '00', null, '20231017144704', '20231017144704', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_10801', 'CIPS_10801', 'CIPS', 1, 'libcips_txn.so', null, null, '00', null, '20231017144705', '20231017144705', null, null, null, null, null);

INSERT INTO G_FUNS (FUN_ID, FUN_NAME, SYSTEM, PARA_NUM, LIB_FILE, FUN_VER, FUN_TYPE, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB_CIPS_PDNG_NOTICE', 'SCB', null, 'libscb_notice.so', null, null, '00', null, '2024017164700', '2024017164700', null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('CIPS_10801', 'CIPS', null, null, null, 'CIPS_MADE_MAIN', 'CIPS_HTTP', 'SERVICE', null, null, null, '费用扣款通知录入', null, '00', null, null, null, null, null, null, null, null);

INSERT INTO G_SERVICES (SERVICE_ID, SYSTEM, SERVICE_TYPE, REQ_OBJ_TYPE, RSP_OBJ_TYPE, SERVICE_FUN, DOCK, DOCK_TYPE, SERVICE_URI, ERR_SERVICE, PRIORITY, REMARKS, SERVICE_VER, STATUS, EXPIRE, UPD_TIME, CRT_TIME, RSV1, RSV2, RSV3, RSV4, RSV5)
VALUES ('SCB_CIPS_PDNG_NOTICE', 'SCB', null, null, null, 'SCB_CIPS_PDNG_NOTICE', 'DEFAULT', 'SERVICE', null, null, null, '检查清算排队数据提醒函数', null, '00', 0, null, null, null, null, null, null, null);